//go:build !ignore_autogenerated

/*
Copyright 2025 Dan Manners.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActDeployment) DeepCopyInto(out *ActDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActDeployment.
func (in *ActDeployment) DeepCopy() *ActDeployment {
	if in == nil {
		return nil
	}
	out := new(ActDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActDeploymentList) DeepCopyInto(out *ActDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActDeploymentList.
func (in *ActDeploymentList) DeepCopy() *ActDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ActDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActDeploymentSpec) DeepCopyInto(out *ActDeploymentSpec) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MinRunners != nil {
		in, out := &in.MinRunners, &out.MinRunners
		*out = new(int32)
		**out = **in
	}
	if in.MaxRunners != nil {
		in, out := &in.MaxRunners, &out.MaxRunners
		*out = new(int32)
		**out = **in
	}
	in.ListenerTemplate.DeepCopyInto(&out.ListenerTemplate)
	in.RunnerTemplate.DeepCopyInto(&out.RunnerTemplate)
	if in.DockerConfigMapRef != nil {
		in, out := &in.DockerConfigMapRef, &out.DockerConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActDeploymentSpec.
func (in *ActDeploymentSpec) DeepCopy() *ActDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ActDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActDeploymentStatus) DeepCopyInto(out *ActDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActDeploymentStatus.
func (in *ActDeploymentStatus) DeepCopy() *ActDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ActDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActRunner) DeepCopyInto(out *ActRunner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActRunner.
func (in *ActRunner) DeepCopy() *ActRunner {
	if in == nil {
		return nil
	}
	out := new(ActRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActRunner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActRunnerList) DeepCopyInto(out *ActRunnerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActRunner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActRunnerList.
func (in *ActRunnerList) DeepCopy() *ActRunnerList {
	if in == nil {
		return nil
	}
	out := new(ActRunnerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActRunnerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActRunnerSpec) DeepCopyInto(out *ActRunnerSpec) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
	out.RegistrationTokenSecretRef = in.RegistrationTokenSecretRef
	if in.DockerConfigMapRef != nil {
		in, out := &in.DockerConfigMapRef, &out.DockerConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	in.JobData.DeepCopyInto(&out.JobData)
	in.JobTemplate.DeepCopyInto(&out.JobTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActRunnerSpec.
func (in *ActRunnerSpec) DeepCopy() *ActRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(ActRunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActRunnerStatus) DeepCopyInto(out *ActRunnerStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActRunnerStatus.
func (in *ActRunnerStatus) DeepCopy() *ActRunnerStatus {
	if in == nil {
		return nil
	}
	out := new(ActRunnerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobData) DeepCopyInto(out *JobData) {
	*out = *in
	if in.Needs != nil {
		in, out := &in.Needs, &out.Needs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunsOn != nil {
		in, out := &in.RunsOn, &out.RunsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobData.
func (in *JobData) DeepCopy() *JobData {
	if in == nil {
		return nil
	}
	out := new(JobData)
	in.DeepCopyInto(out)
	return out
}
